// <auto-generated />
using System;
using DataEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntity.Migrations
{
    [DbContext(typeof(SkladContext))]
    [Migration("20251015071241_UpdateAfterChange")]
    partial class UpdateAfterChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataEntity.Data.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<DateTime>("DatumPridani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MernaJednotkaID")
                        .HasColumnType("int");

                    b.Property<int>("MnoDoPal")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("MnozPoj")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaterialID");

                    b.HasIndex("MernaJednotkaID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("DataEntity.Data.MerneJednotky", b =>
                {
                    b.Property<int>("MernaJednotkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MernaJednotkaID"));

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MernaJednotkaID");

                    b.ToTable("MerneJednotky");
                });

            modelBuilder.Entity("DataEntity.Data.Material", b =>
                {
                    b.HasOne("DataEntity.Data.MerneJednotky", "MernaJednotka")
                        .WithMany("Materials")
                        .HasForeignKey("MernaJednotkaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MernaJednotka");
                });

            modelBuilder.Entity("DataEntity.Data.MerneJednotky", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
